site_name: "Hexu Zhao's Homepage"
site_author: 'Hexu Zhao'
copyright: '&copy; 2022-2023 Hexu Zhao'
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: white
    accent: orange
  favicon: images/nyulogo.png
  icon:
    logo: material/account-school
    
plugins:
  []
  
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra:
  social:
    - icon: fontawesome/solid/envelope 
      link: mailto:hz3496@nyu.edu
    - icon: academicons/google-scholar
      link: https://scholar.google.com/citations?user=ylKFMAkAAAAJ&hl=en
    - icon: academicons/semantic-scholar
      link: https://www.semanticscholar.org/author/Xichen-Pan/2158877024
    - icon: academicons/dblp
      link: https://dblp.org/pid/293/9714.html
    - icon: fontawesome/brands/github 
      link: https://github.com/tarzanzhao
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/hexu-zhao-203304244/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/xichen_pan
    - icon: fontawesome/brands/zhihu 
      link: https://www.zhihu.com/people/zhao-he-xu-61
  analytics:
    provider: google
    property: G-KBQPT9Q9MJ
extra_css:
  - stylesheets/extra.css 
